### ISSUE TITLE
Installing on Ubuntu 

### ISSUE THREAD

**Issue by kkr007** [fluent/fluent-plugin-windows-eventlog#109]
Hi new to windows plugin.

Can i install this on Linux? as i facing issue installing

compiling winevt.c
In file included from winevt.c:1:
./winevt_c.h:8:10: fatal error: w32api.h: No such file or directory
    8 | #include <w32api.h>
      |          ^~~~~~~~~~
compilation terminated.
make: *** [Makefile:245: winevt.o] Error 1

I have tried installing mingw too still same error

**Comment by kenhys** [comment]
This plugin is not designed to be used on Linux.

**Comment by daipom** [comment]
Why do you want to install Windows plugin on Linux?

**Comment by kkr007** [comment]
I was testing if I could use the Linux system to collect Windows logs remotely, as nowadays cross platform library is now available. Linux is widely use and plus free to use.

**Comment by daipom** [comment]
I see!
Currently, we can't install this plugin on Linux, as @kenhys says.
I think it is because this plugin directly depends on win32 API.

Since we can transfer data between multiple Fluentd's using `in_forward` and `out_forward`, we need to install Fluentd on that Windows and transfer the collected event logs.
